# Generated by Django 5.2.6 on 2025-10-17 16:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_nombre', models.CharField(max_length=100)),
                ('categoria_descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CentroDistribucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_nombre', models.CharField(max_length=100)),
                ('id_direccion', models.IntegerField(blank=True, null=True)),
                ('centro_tipo', models.CharField(choices=[('distribuidor', 'Distribuidor'), ('quiosco', 'Quiosco'), ('tienda', 'Tienda')], max_length=20)),
                ('centro_descripcion', models.TextField(blank=True, help_text='Descripción de los productos que se venden en este centro', null=True)),
                ('centro_imagen', models.ImageField(blank=True, null=True, upload_to='centros_distribucion/')),
            ],
        ),
        migrations.CreateModel(
            name='ContactoCentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_centro', models.IntegerField(blank=True, null=True)),
                ('contacto_tipo', models.CharField(choices=[('telefono', 'Teléfono'), ('correo', 'Correo'), ('whatsapp', 'WhatsApp')], max_length=10)),
                ('contacto_valor', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_calle', models.CharField(max_length=255)),
                ('direccion_ciudad', models.CharField(max_length=100)),
                ('direccion_region', models.CharField(max_length=100)),
                ('direccion_pais', models.CharField(max_length=100)),
                ('direccion_codigo_postal', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_inventario', models.IntegerField(blank=True, null=True)),
                ('id_usuario', models.IntegerField(blank=True, null=True)),
                ('historial_tipo_movimiento', models.CharField(choices=[('agregar', 'Agregar'), ('retirar', 'Retirar'), ('traslado', 'Traslado')], max_length=10)),
                ('id_centro_destino', models.IntegerField(blank=True, null=True)),
                ('historial_cantidad', models.IntegerField()),
                ('historial_fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.CharField(max_length=100)),
                ('producto_descripcion', models.TextField(blank=True, null=True)),
                ('id_categoria', models.IntegerField(blank=True, null=True)),
                ('producto_precio', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('producto_estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('producto_imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoValorNutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.IntegerField(blank=True, null=True)),
                ('valor_calorias', models.IntegerField(blank=True, null=True)),
                ('valor_proteinas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('valor_carbohidratos', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('valor_grasas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('valor_fibra', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('valor_sodio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('valor_azucar', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor_nombre', models.CharField(max_length=100)),
                ('proveedor_rut', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('proveedor_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('proveedor_telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('id_direccion', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('usuario_nombre', models.CharField(blank=True, max_length=50)),
                ('usuario_apellido', models.CharField(blank=True, max_length=50)),
                ('usuario_rut', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('usuario_email', models.EmailField(max_length=254, unique=True)),
                ('usuario_rol', models.CharField(choices=[('cliente', 'Cliente'), ('admin', 'Administrador')], default='cliente', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FavoritoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField(blank=True, null=True)),
                ('id_producto', models.IntegerField(blank=True, null=True)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('id_usuario', 'id_producto')},
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_centro', models.IntegerField(blank=True, null=True)),
                ('id_producto', models.IntegerField(blank=True, null=True)),
                ('inventario_cantidad', models.IntegerField()),
            ],
            options={
                'unique_together': {('id_centro', 'id_producto')},
            },
        ),
    ]
