# Generated by Django 5.2.6 on 2025-10-03 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verdeLimonApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_nombre', models.CharField(max_length=100)),
                ('categoria_descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CentroDistribucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_nombre', models.CharField(max_length=100)),
                ('centro_tipo', models.CharField(choices=[('distribuidor', 'Distribuidor'), ('quiosco', 'Quiosco'), ('tienda', 'Tienda')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_calle', models.CharField(max_length=255)),
                ('direccion_ciudad', models.CharField(max_length=100)),
                ('direccion_region', models.CharField(max_length=100)),
                ('direccion_pais', models.CharField(max_length=100)),
                ('direccion_codigo_postal', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.CharField(max_length=100)),
                ('producto_descripcion', models.TextField(blank=True, null=True)),
                ('producto_precio_referencial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('producto_estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verdeLimonApp.categoriaproducto')),
            ],
        ),
        migrations.CreateModel(
            name='ContactoCentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto_tipo', models.CharField(choices=[('telefono', 'Teléfono'), ('correo', 'Correo'), ('whatsapp', 'WhatsApp')], max_length=10)),
                ('contacto_valor', models.CharField(max_length=255)),
                ('id_centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verdeLimonApp.centrodistribucion')),
            ],
        ),
        migrations.AddField(
            model_name='centrodistribucion',
            name='id_direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verdeLimonApp.direccion'),
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventario_cantidad', models.IntegerField()),
                ('id_centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verdeLimonApp.centrodistribucion')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verdeLimonApp.producto')),
            ],
            options={
                'unique_together': {('id_centro', 'id_producto')},
            },
        ),
        migrations.CreateModel(
            name='HistorialInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historial_tipo_movimiento', models.CharField(choices=[('agregar', 'Agregar'), ('retirar', 'Retirar'), ('traslado', 'Traslado')], max_length=10)),
                ('historial_cantidad', models.IntegerField()),
                ('historial_fecha', models.DateTimeField(auto_now_add=True)),
                ('id_centro_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_destino', to='verdeLimonApp.centrodistribucion')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verdeLimonApp.inventario')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoValorNutricional',
            fields=[
                ('id_producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='verdeLimonApp.producto')),
                ('calorias', models.IntegerField(blank=True, null=True)),
                ('proteinas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('carbohidratos', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grasas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fibra', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sodio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('azucar', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor_nombre', models.CharField(max_length=100)),
                ('proveedor_rut', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('proveedor_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('proveedor_telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('proveedor_direccion_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='verdeLimonApp.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='UbicacionCentro',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion_latitud', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('ubicacion_longitud', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('ubicacion_referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('id_centro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='verdeLimonApp.centrodistribucion')),
            ],
        ),
        migrations.CreateModel(
            name='FavoritoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verdeLimonApp.producto')),
            ],
            options={
                'unique_together': {('id_usuario', 'id_producto')},
            },
        ),
    ]
