# Generated by Django 5.2.6 on 2025-10-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verdeLimonApp', '0002_categoriaproducto_centrodistribucion_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrodistribucion',
            name='centro_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='centros_distribucion/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='producto_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
