# Generated by Django 5.2.6 on 2025-10-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verdeLimonApp', '0003_centrodistribucion_centro_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrodistribucion',
            name='centro_descripcion',
            field=models.TextField(blank=True, help_text='Descripción de los productos que se venden en este centro', null=True),
        ),
    ]
