# Generated by Django 5.2.6 on 2025-10-04 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verdeLimonApp', '0004_centrodistribucion_centro_descripcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UbicacionCentro',
        ),
    ]
