# Generated by Django 5.2.6 on 2025-10-04 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verdeLimonApp', '0005_delete_ubicacioncentro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productovalornutricional',
            old_name='azucar',
            new_name='valor_azucar',
        ),
        migrations.RenameField(
            model_name='productovalornutricional',
            old_name='calorias',
            new_name='valor_calorias',
        ),
        migrations.RenameField(
            model_name='productovalornutricional',
            old_name='carbohidratos',
            new_name='valor_carbohidratos',
        ),
        migrations.RenameField(
            model_name='productovalornutricional',
            old_name='fibra',
            new_name='valor_fibra',
        ),
        migrations.RenameField(
            model_name='productovalornutricional',
            old_name='grasas',
            new_name='valor_grasas',
        ),
        migrations.RenameField(
            model_name='productovalornutricional',
            old_name='proteinas',
            new_name='valor_proteinas',
        ),
        migrations.RenameField(
            model_name='productovalornutricional',
            old_name='sodio',
            new_name='valor_sodio',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='producto_precio_referencial',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='proveedor_direccion_id',
        ),
        migrations.AddField(
            model_name='producto',
            name='producto_precio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='id_direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedores', to='verdeLimonApp.direccion'),
        ),
    ]
